# memex configuration

vault:
  path: ~/Documents/Note/00-memex/

slack:
  watch_channels:
    - name: "pd-emr-k部"
      limit: 50
    - name: "pd-emr-eiyou"
      limit: 50
    - name: "pd-backend"
      limit: 50
    - name: "pd-frontend"
      limit: 50
